### ISSUE TITLE
Got exception Exception in thread "main" java.lang.ClassNotFoundException: com.regexlab.j2e.demo.DemoWebApplication

### ISSUE THREAD

**Issue by dk2k** [sswater/demo-spring-boot-parent#1]
Full stack:
Exception in thread "main" java.lang.ClassNotFoundException: com.regexlab.j2e.demo.DemoWebApplication
        at java.net.URLClassLoader.findClass(Unknown Source)
        at com.regexlab.j2e.Jar2ExeClassLoader.findClass(Jar2ExeClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at com.regexlab.j2e.Jar2ExeLauncher.main(Jar2ExeLauncher.java:48)

**Comment by dk2k** [comment]
Is this input of class com.regexlab.j2e.demo.DemoWebApplication valid only for this project? Or is it valid for any custom project?

**Comment by dk2k** [comment]
I see now. I should specify my actual Application class and the wizard will ask if I'm sure anyway.
From the guide I understood that I need to specify com.regexlab.j2e.demo.DemoWebApplication in all cases - as if it is substituted somewhere in the processing to the actual classname.
